### 
GET   http://localhost:3001/
Content-Type: application/json
### 
GET   http://localhost:3001/universities/all
Content-Type: application/json

###
GET   http://localhost:3001/universities/target
Content-Type: application/json

### 
POST  http://localhost:3001/universities
Content-Type: application/json


   {
        "name":"z",
        "category":"reach",
        "application_submitted":false
    } 



### 
PATCH  http://localhost:3001/universities
Content-Type: application/json

{
    "school_id":2
}

### 
PATCH  http://localhost:3001/universities
Content-Type: application/json

{
    "school_id":2,
    "category":"none"
}


### 

DELETE   http://localhost:3001/universities
Content-Type: application/json
